input_dir: ${PROJECT_DIR}/Calendr
output_dir: ${PROJECT_DIR}/Calendr

strings:
  inputs: Assets/en.lproj
  outputs:
    - templateName: structured-swift5
      output: Constants/Strings.generated.swift
      params:
        enumName: Strings
